[package]
name = "encodedvenom/ragdolldaemon"
description = "Ragdoll Daemon"
version = "0.0.1"
license = "MIT"
authors = ["EncodedVenom"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Component = "sleitnick/component@^2"